function d_px_euler = d_px_euler(X11,Y11,Z11,rpy12,rpy13)
%D_PX_EULER
%    D_PX_EULER = D_PX_EULER(X11,Y11,Z11,RPY12,RPY13)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    08-Sep-2020 13:53:12

t2 = (rpy12.*pi)./1.8e+2;
t3 = (rpy13.*pi)./1.8e+2;
t4 = cos(t2);
t5 = cos(t3);
t6 = sin(t2);
t7 = sin(t3);
d_px_euler = [0.0,(Z11.*t4.*pi)./1.8e+2-(X11.*t5.*t6.*pi)./1.8e+2+(Y11.*t6.*t7.*pi)./1.8e+2,t4.*pi.*(X11.*t7+Y11.*t5).*(-1.0./1.8e+2),1.0,0.0,0.0];
