function d_pz_euler = d_pz_euler(X11,Y11,Z11,rpy11,rpy12,rpy13)
%D_PZ_EULER
%    D_PZ_EULER = D_PZ_EULER(X11,Y11,Z11,RPY11,RPY12,RPY13)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    08-Sep-2020 13:53:12

t2 = (rpy11.*pi)./1.8e+2;
t3 = (rpy12.*pi)./1.8e+2;
t4 = (rpy13.*pi)./1.8e+2;
t5 = cos(t2);
t6 = cos(t3);
t7 = cos(t4);
t8 = sin(t2);
t9 = sin(t3);
t10 = sin(t4);
d_pz_euler = [X11.*((t5.*t10.*pi)./1.8e+2+(t7.*t8.*t9.*pi)./1.8e+2)+Y11.*((t5.*t7.*pi)./1.8e+2-(t8.*t9.*t10.*pi)./1.8e+2)-(Z11.*t6.*t8.*pi)./1.8e+2,t5.*pi.*(Z11.*t9+X11.*t6.*t7-Y11.*t6.*t10).*(-1.0./1.8e+2),X11.*((t7.*t8.*pi)./1.8e+2+(t5.*t9.*t10.*pi)./1.8e+2)-Y11.*((t8.*t10.*pi)./1.8e+2-(t5.*t7.*t9.*pi)./1.8e+2),0.0,0.0,1.0];
